spring:
  application:
    name: iptablecommandcode-service
  config:
    import: "optional:configserver:http://192.168.117.210:8888"
#    로컬 개발시 import: "optional:configserver:http://127.0.0.1:8888" 처리 요망

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh